# App Info
ios_app_id                                : 1532609651                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             : https://apps.apple.com/fr/app/mami-nianga/id1532609651                                          # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.maminianga.maminianga                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file).
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Votre site sera bientôt Nianga                                        # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Commandez votre coiffure à domicile!

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : CGV
your_link                                 : /CGV_Mami_Nianga.pdf
# your_city                                 : Paris
email_address                             : contact@maminianga.com
facebook_username                         : mami.nianga.31
instagram_username                        : maminianga
# twitter_username                          : ebaehr
# github_username                           : emilbaehr
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  # - title                                 : La liste mise à jour de tous les clubs de la capitale
  #   description                           : Retrouvez tous les clubs ouverts (verts) ou en ouverture prochaine (rouge)
  #   fontawesome_icon_name                 : clipboard check
  #
  # - title                                 : Soyez prévenus des nouvelles ouvertures
  #   description                           : Activez les notifications et soyez les premiers prevenus de l'ouverture d'un club!
  #   fontawesome_icon_name                 : bell

  - title                                 : 1. Moyen de paiement
    description                           : Pour des raisons de sécurité et sanitaires, nous ne pratiquons pas le paiement en espèces. Tous les règlements s'effectuent uniquement sur l'application (Mobile Money ou Carte bancaire).
    fontawesome_icon_name                 : trophy

  - title                                 : 2. Ma coiffure n'est pas dans la liste
    description                           : N'hésitez pas à nous faire savoir vos choix de coiffure, nous enrichirons notre offre. Nos talents savent s'adapter.
    fontawesome_icon_name                 : clock

  - title                                 : 3. Est-il possible d'annuler une réservation?
    description                           : Oui, vous avez jusqu'à la veille de la date prévue de votre prestation pour annuler sans frais. Nous procéderons alors au remboursement de l'acompte versé sur le numéro indiqué à votre profil.
    fontawesome_icon_name                 : phone

# Feature List                            Edit, add or remove features to be presented.
faq                                  :

  # - title                                 : La liste mise à jour de tous les clubs de la capitale
  #   description                           : Retrouvez tous les clubs ouverts (verts) ou en ouverture prochaine (rouge)
  #   fontawesome_icon_name                 : clipboard check
  #
  # - title                                 : Soyez prévenus des nouvelles ouvertures
  #   description                           : Activez les notifications et soyez les premiers prevenus de l'ouverture d'un club!
  #   fontawesome_icon_name                 : bell

  - title                                 : 1. Moyen de paiement
    description                           : Pour des raisons de sécurité et sanitaires, nous ne pratiquons pas le paiement en espèces. Tous les règlements s'effectuent uniquement sur l'application (Mobile Money ou Carte bancaire).

  - title                                 : 2. Ma coiffure n'est pas dans la liste
    description                           : N'hésitez pas à nous faire savoir vos choix de coiffure, nous enrichirons notre offre. Nos talents savent s'adapter.

  - title                                 : 3. Est-il possible d'annuler une réservation?
    description                           : Oui, vous avez jusqu'à la veille de la date prévue de votre prestation pour annuler sans frais. Nous procéderons alors au remboursement de l'acompte versé sur le numéro indiqué à votre profil.
  # - title                                 : Feature List
  #   description                           : Add features (like this one) to your site via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : star
  #
  # - title                                 : Smart App Banner
  #   description                           : Display a smart app banner on iOS devices.
  #   fontawesome_icon_name                 : arrow-alt-circle-down
  #
  # - title                                 : Social Links
  #   description                           : Easily add social media accounts and contact info in the footer via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : link
  #
  # - title                                 : FontAwesome Support
  #   description                           : Pick custom Font Awesome icons for the feature list via the _config.yml file. No HTML/CSS needed.
  #   fontawesome_icon_name                 : info-circle
  #
  # - title                                 : # New Feature Title
  #   description                           : # New Feature Description
  #   fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0
topbar_title_color                        : "#ffffff"

cover_image                               : assets/site_web.jpg                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.3

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#E4B332"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME
